### ISSUE TITLE
Reveal has disappeared?

### ISSUE THREAD

**Issue by dmg46664** [practicalli/clojure-cli-config#68]
I had a setup for debugging some hairy recursive code using Reveal (no reveal specific code required in my app).

Now I return a month or so later and it's gone? [diff here.](https://github.com/practicalli/clojure-deps-edn/commit/88240512555c69ff104c5ffec2dd094f9b8a44d9#diff-982df435489d5c84c0cb933bd9a5f4b9298c5cff07742c7fffa8788bbd9b1d6bR189)

How do you evaluate that something is 'unused'? Can you keep metrics on `clojure-deps-edn` alias downloads?

With Portal I seem to have to launch an inspector from within the app. Extra steps for me given it's HumbleUI and can crash if I am doing crazy things.

Also it feels very un-Clojure like that these aliases are mutable and removed (thinking of Rich Hickey's talk and the blessings of Maven immutability).

My code tap>s out reams of info, which was very smooth scrolling through in Reveal (order is important for analysis). Perhaps I can get Portal to the same place.. but will require investigative work and so is jarring.

Thanks for the project and looking forward to your thoughts on this issue.

**Comment by practicalli-john** [comment]
Portal can be figured to listen to all evaluations over nREPL connection using the `portal.nrepl/wrap-portal` middleware in the alias and using the `portal.api/submit` call once portal is open (usually via a `user` namespace.
https://practical.li/clojure/data-inspector/portal/#send-to-portal

I do not understand if this meets you requirements though.

## Deprecated aliases
The reveal related aliases have been deprecated and moved to the `deps-deprecated.edn` file.

Announcement was made in 2023-02-02 via the Clojurians Slack community
https://clojurians.slack.com/archives/C06MAR553/p1675391136099759

I can only gauge my own use of aliases in this configuration.  When there is constructive feedback and suggestions I can factor that into the design of aliases.  Feedback is very infrequent though.

I do not know of any mechanism to monitor who is using which alias and do not wish to force people to share usage statistics.  It is expected that limited feedback would be received if users had a means to volunteer usage information. 

The main focus of alias design is to support the workflow used by Practicalli which evolves over time.
Reveal has always been complicated and not a natural fit for how Practicalli works and the aliases have been complicated in their design also.

I do occasionally add aliases to the configuration on request, although not all of these will be included in the project README or in any of the Practicalli content.

If there is a specific Reveal alias which you find valuable, I can add it back to the config.edn file and it will receive library updates along with other aliases.

If you wish to supply any documentation on using Reveal, especially features that are not part of other tooling, then that can be considered.  Note that as Reveal is part commercial project, I prefer not to include content that required purchasing a licence.

**Comment by dmg46664** [comment]
Thanks for the reply.
I looked at the announcement comment but didn't see Reveal mentioned.
I have added a Reveal alias to my project locally which suffices for now, although I did test Portal tapping> around 2000 maps of 10 pairs each and it slowed to an absolute crawl... while Reveal handles scrolling top to bottom and back in a split second.

**Comment by practicalli-john** [comment]
Suggest forking the Practicalli repository and adding your own.  Or simply copy parts of the practicalli configuration into your

Apart from library version updates, I am not planning on adding new aliases unless there is very clear value to their use.
