### ISSUE TITLE
clj-kondo improvements

### ISSUE THREAD

**Issue by vemv** [practicalli/clojure-cli-config#72]
Hey there!

Thanks for your project. I'm experimenting with using it as my source of truth for all sorts of CI checks i.e. not just for personal productivity.

I noticed a couple possible issues with the clj-kondo setup:

* `:main-opts  ["-m" "clj-kondo.main" "--lint" "src"]}` does not specify `"test"`. This seems a dangerous absence to have by default. It would seem sensible to either drop `src` or to also include `test`.
* For best results, clj-kondo shouldn't be run as a one-liner, see e.g. https://github.com/clj-kondo/clj-kondo#project-setup. So it seems to me that there should be an additional alias?
  *  The usage I would foresee is `clojure -M:lint/clj-kondo.analyse && clojure -M:lint/clj-kondo src test`

wdyt?

Cheers - V

**Comment by practicalli-john** [comment]
I dont believe I've actually used the `:lint/clj-kondo` alias or found a need to use it, so the initial though is to deprecate that alias.  I havent used the eastwood or kibit runners either.  

For Continuous Integration, I use [Setup Clojure GitHub action](https://github.com/marketplace/actions/setup-clojure) which uses the clj-kondo binary and is simple to use

I've started documenting the CI actions and workflows I use in the [Practicalli Engineering Playbook](https://practical.li/engineering-playbook/continuous-integration/github-actions/)

For local development, I've always recommend installing the clj-kondo binary and use it for live linting with a Clojure editor, either directly or via Clojure-LSP.  Emacs, Neovim and VS Code all support Clojure-LSP and live linting with clj-kondo.

I also have several GitHub workflows that run clj-kondo, including MegaLinter which I can also use to run clj-kondo locally along with a host of other linters.

clj-kondo will run significantly faster a binary, compared to running it through the JVM using the `clojure` command and the `:lint/clj-kondo alias, especially on larger projects.

As correctly mentioned that clj-kondo should also be run once to create a cache of the project and a second time to create a full analysis, then this would make it far slower to use clj-kondo from the Practicalli CLI Config.

So whist I can add a further alias for the clj-kondo anaylsis of a project, I am not clear on what a valuable use case is for doing so.  Without further understanding, I'm not sure I'd want to document and advocate using aliases to use this type of tool.

I am also not clear on what the `:main-opts` would look like if the class path has to be calculated from all the dependencies.  I dont believe I can run `clojure -Spath` from within an alias `:main-opts`, so this may be a limiting factor (I think I had this issue with one of the security aliases last year)

So I would only use clj-kondo from an alias if there were no other mechanism available.

**Comment by practicalli-john** [comment]
I will keep the `:lint/clj-kondo` alias in the Practicalli Clojure CLI Config as I can see it can be useful for other CI services 

I will accept PRs to change to the design of the alias, e.g. the :main-opts or just confirm what they should be on this issue.

I don't typically check unit test code within a CI workflow, as that code is not going to be deployed.

If there is a solution to the original analysis via clj-kondo within an alias, then I will consider adding it to the Practicalli config

Unfortunately looking for a solution to that analysis is way down my list of TODOs I am afraid

If I do bump into anything useful then I'll report back.
Thank you

**Comment by practicalli-johnny** [comment]
Although I am sure nvd-clojure works well as a tool, it doesnt seem to fit well using it from a Clojure user configuration.

Unless I have missed some approach to make this work within the constrains of a `deps.edn file, I intend to drop nvd-clojure from the Practicalli user configuration.

I will try out https://github.com/clj-holmes/clj-watson which seems to be a better fit as an alias
