### ISSUE TITLE
deps-new Invalid Tag

### ISSUE THREAD

**Issue by jcrum** [practicalli/clojure-cli-config#80]
When creating a new service from the template I get an error for io.github.seancorfield/deps-new stating that the tag (0.6.0) is invalid.   
<img width="627" alt="Screenshot 2024-01-03 at 22 39 42" src="https://github.com/practicalli/clojure-cli-config/assets/527053/e8c008d3-2bcc-4095-bfa3-371c7afca01f">

Changing the tag for io.github.seancorfield/deps-new in deps.edn to 'v0.6.0' fixes the issue. 

I will submit a pull request.

**Comment by practicalli-johnny** [comment]
Thanks.  Sorry for the copy paste error.
