### ISSUE TITLE
Command line arguments to repl/rebel-remote don't work

### ISSUE THREAD

**Issue by toburger** [practicalli/clojure-cli-config#82]
The same command line args as applied to repl/remote do not work with repl/rebel-remote.
--host and --port do not have any effect.

**Comment by practicalli-johnny** [comment]
Maybe I am missing something but I havent been able to replicate the issue you have been experiencing

![image](https://github.com/practicalli/clojure-cli-config/assets/250870/90060925-6faa-4469-bf5e-0cc3d4480ef0)

Are the more details you can supply, e.g. the command used, any network infrastructure being navigated or a project that recreates the issue.

Thanks.

**Comment by toburger** [comment]
After investigating a bit more I think I've found the "real" cause of the problem:

The remote NREPL gets registered with the host localhost and (see the printed out nrepl://localhost:44947:

![image](https://github.com/practicalli/clojure-cli-config/assets/728782/c77ee0a2-2615-45a6-9635-d9422835cd4c)

When i execute a netcat command I can't reach the service:

![image](https://github.com/practicalli/clojure-cli-config/assets/728782/20448fb9-147b-4c17-beb0-6c0321bfe650)

So I think I have to start the nrepl-Server correctly. The `repl/...` commands do have a parameter to specify the host name?

**Comment by toburger** [comment]
Ah, that's exactly what happened! I've tried it with --host and nothing happened so I thought there is no option for that! 😅 Thanks for the hint!

Now the `repl/remote` works like a charm. But the `repl/rebel-remote` doesn't seem to use the --host argument.

<img width="887" alt="image" src="https://github.com/practicalli/clojure-cli-config/assets/728782/ea8c13fd-2122-4da4-99c8-34928c8fca22">

Sorry, I had to hide the host for security reasons but I can assure that the they go to the same host.

**Comment by practicalli-johnny** [comment]
I believe the `--connect` option is also required as well as the `--host` and `--port` options

```shell
clojure -M:repl/rebel-remote --connect --host hostname --port 8083
```

I dont have a remote setup at the moment to test.  

If the above doesnt work, then try using nrepl directly as a remote REPL client
https://nrepl.org/nrepl/usage/clients.html#using-the-built-in-client

**Comment by practicalli-johnny** [comment]
If using Emacs Cider as the local REPL connection, define a local SSH connection in the `.ssh/config` file.

```config
Host gkar-repl
  HostName 192.168.0.238
  # IdentityFile /home/practicalli/.local/joint-clojure-machine.pem
  User practicalli
  PasswordAuthentication yes
  LocalForward 1234 localhost:1234
  Port 22
```
> Uncomment the `IdentityFile` if there are pem certificates available.  Otherwise Emacs Cider will prompt for the user account password on the remote machine.

In Emacs, run the `cider-connect-clj` command and select the Host definition from the list of connections, e.g. gkar-repl or enter the IP address of the remote server

Enter the port, e.g 1234

Emacs cider should connect to the remote repl state.

**Comment by toburger** [comment]
Thanks for the thorough testing!
I've managed to connect via SSH tunnel and Cider and it works!

But in summary we can definitely say that `repl/rebel-remote` ignores --host and --port parameters.

![image](https://github.com/practicalli/clojure-cli-config/assets/728782/92641a7d-aa5b-4ebc-8d30-22765cb2ae01)

Which is fine for me if I know the limitations but on the other hand the command is misleading as it implies that it is possible to connect to a remote REPL.

**Comment by practicalli-johnny** [comment]
Marked the alias as DEPRECATED and will move to the deps-deprecated.edn file by the next release
